export const MarketFactoryABI = [
  {
    type: "function",
    name: "createMarket",
    inputs: [
      { name: "question", type: "string", internalType: "string" },
      { name: "outcomes", type: "string[]", internalType: "string[]" },
      { name: "resolutionTime", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getMarket",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      {
        name: "market",
        type: "tuple",
        internalType: "struct IMarketFactory.Market",
        components: [
          { name: "marketId", type: "bytes32", internalType: "bytes32" },
          { name: "question", type: "string", internalType: "string" },
          { name: "outcomes", type: "string[]", internalType: "string[]" },
          { name: "resolutionTime", type: "uint256", internalType: "uint256" },
          { name: "winningOutcome", type: "uint8", internalType: "uint8" },
          { name: "resolved", type: "bool", internalType: "bool" },
          { name: "creator", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketCount",
    inputs: [],
    outputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketIdAt",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOutcomes",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "outcomes", type: "string[]", internalType: "string[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isMarketResolved",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "marketExists",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "exists", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWinningOutcome",
    inputs: [{ name: "marketId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "MarketCreated",
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "question", type: "string", indexed: false, internalType: "string" },
      { name: "outcomes", type: "string[]", indexed: false, internalType: "string[]" },
      { name: "resolutionTime", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "creator", type: "address", indexed: true, internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "MarketResolved",
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "winningOutcome", type: "uint8", indexed: false, internalType: "uint8" },
    ],
  },
  {
    type: "function",
    name: "whitelisted",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
] as const;
